### ISSUE TITLE
Will there be more builds released in this repo?

### ISSUE THREAD

**Issue by lengran** [robimarko/openwrt#102]
### Describe the bug

Hi! Thanks for the great work you have done. I have been using your firmware for a long time. I noticed that you have been working on ath11k related branch for a while and there have been no firmware released since 2023-1. So I wonder if I should switch to firmware on the official website or I should keep waiting for your next build?

Also I checked the firmware on the official website. It seems that the firmware provided there is not compatible with the firmware you provided. Neither does the former one provide luci packages, nor does it susupgrade pass the version check during the update process. If I want to switch to the official releases, should I do a fresh reinstall? (I'm currently using release [Updated prebuilt images 2023-01-14-1709])

Thanks.

### OpenWrt version

r0-3a2144f

### OpenWrt target/subtarget

ipq807x/generic

### Device

Redmi AX6

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
No, there won't be any new releases since everything has been upstreamed.
If you are on compat version 2.0 then you can simply force sysupgrade onto the official OpenWrt snapshot
