### ISSUE TITLE
How to switch to version 23.05.2？

### ISSUE THREAD

**Issue by AxIauk** [robimarko/openwrt#103]
### Describe the bug

nano feeds.conf.default
rc-git packages https://git.openwrt.org/feed/packages.git;openwrt-23.05
src-git luci https://git.openwrt.org/project/luci.git;openwrt-23.05
src-git routing https://git.openwrt.org/feed/routing.git;openwrt-23.05
src-git telephony https://git.openwrt.org/feed/telephony.git;openwrt-23.05

or
23.05.2
src-git packages https://git.openwrt.org/feed/packages.git^8e3a18246
src-git luci https://git.openwrt.org/project/luci.git^7739e9f5b0
src-git routing https://git.openwrt.org/feed/routing.git^83ef378
src-git telephony https://git.openwrt.org/feed/telephony.git^9746ae8

It seems that this change is invalid.

### OpenWrt version

snapshot-r0-81e9fae

### OpenWrt target/subtarget

snapshot-r0-81e9fae

### Device

rt-ax89x

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
There is no way
