### ISSUE TITLE
Xiaomi AX3600 Brick After flash the latest update

### ISSUE THREAD

**Issue by omensight** [robimarko/openwrt#50]
Hello, I have bricked my Router Xiaomi AX3600 after flashing the latest release, I have tried to unbrick my device with this guide without success https://openwrt.org/inbox/toh/xiaomi/xiaomi_ax3600#debricking, I would like to grab your help, thanks in advance.

**Comment by robimarko** [comment]
You are gonna have to hook up UART

**Comment by omensight** [comment]
> You are gonna have to hook up UART
Thanks, how could I do that? Do you have some guide I can use?

**Comment by robimarko** [comment]
Its all documented in the wiki:
https://openwrt.org/inbox/toh/xiaomi/xiaomi_ax3600#serial

**Comment by omensight** [comment]
Hi, I'm new in this topic, I have two questions please.
1. Can I use this TTL CP2102 (6Pin) ?
![_c_o_com-05-015-1](https://user-images.githubusercontent.com/34387536/183421422-b4377c0f-3ee1-42e1-a103-fc16447ed4c7.jpg)
2. What do no ttl pin voltage 1.8V  mean?
Thanks in advance.

**Comment by robimarko** [comment]
No, CP2102 is not 1.8V IO.

You must use a 1.8V IO adapter, otherwise you will fry the SoC

**Comment by tm4dev** [comment]
> Hello, I have bricked my Router Xiaomi AX3600 after flashing the latest release, I have tried to unbrick my device with this guide without success https://openwrt.org/inbox/toh/xiaomi/xiaomi_ax3600#debricking, I would like to grab your help, thanks in advance.

Did you try miwifi repair tool? If you didnt modify partitions, I think it can help. It's easy way

**Comment by omensight** [comment]
> > Hello, I have bricked my Router Xiaomi AX3600 after flashing the latest release, I have tried to unbrick my device with this guide without success https://openwrt.org/inbox/toh/xiaomi/xiaomi_ax3600#debricking, I would like to grab your help, thanks in advance.
> 
> Did you try miwifi repair tool? If you didnt modify partitions, I think it can help. It's easy way

Yes, I have tried it yesterday and the flash screen never popped up.

**Comment by tm4dev** [comment]
> > > Hello, I have bricked my Router Xiaomi AX3600 after flashing the latest release, I have tried to unbrick my device with this guide without success https://openwrt.org/inbox/toh/xiaomi/xiaomi_ax3600#debricking, I would like to grab your help, thanks in advance.
> > 
> > 
> > Did you try miwifi repair tool? If you didnt modify partitions, I think it can help. It's easy way
> 
> Yes, I have tried it yesterday and the flash screen never popped up.

yes I know, I have been in your situation. the problem is that tool did not change the network card configuration probably. take a look at the official instruction here https://www.xiaomi.cn/post/19134127

**Comment by joba-1** [comment]
> 2. What do no ttl pin voltage 1.8V  mean?
>    Thanks in advance.

it means the sending/receiving lines expect this voltage and not more.

If you can‘t find one: I use this one:

€ 3,72 | FT232RL serial port module USB to TTL serial port small board 5V 3.3V 1.8V level
https://a.aliexpress.com/_vq2vab

**Comment by omensight** [comment]
> > 2. What do no ttl pin voltage 1.8V  mean?
> >    Thanks in advance.
> 
> it means the sending/receiving lines expect this voltage and not more.
> 
> If you can‘t find one: I use this one:
> 
> € 3,72 | FT232RL serial port module USB to TTL serial port small board 5V 3.3V 1.8V level https://a.aliexpress.com/_vq2vab

So I have to get a 1.8v board? 
![IMG-20220808-WA0001](https://user-images.githubusercontent.com/34387536/183507712-57574922-ca31-473e-b6a8-6954dad682bb.jpg)
I think this one is not good in this case.

**Comment by joba-1** [comment]
it needs to mention 1.8V or it will not have it - it is a not so common voltage.

**Comment by robimarko** [comment]
FT232 ones are usually what you want as they are cheap and support 1.8V

**Comment by omensight** [comment]
> FT232 ones are usually what you want as they are cheap and support 1.8V

I didn't found a 1.8v in my country and in the case I buy it from AliExpress it gonna arrive in my country in three months or more, is there another solution?

**Comment by robimarko** [comment]
There is no way around getting a 1.8V UART adapter, other than frying your CPU

**Comment by robimarko** [comment]
Great to hear that

**Comment by w1ndy** [comment]
> There is no way around getting a 1.8V UART adapter, other than frying your CPU

Just adding my two cents here: Actually I've made successful attempts to repair my AX3600 with a 3.3V adapter... You'll have to start the router only with TXD and RXD connected and plug in GND immediately when the router LED starts to blink

![image](https://user-images.githubusercontent.com/652068/185613362-cb8a557a-8472-4afb-b561-063939ef90d4.png)

**Comment by robimarko** [comment]
That's really risky, pins are 1.8V rated and using 3.3V for any duration can easily fry it.
