### ISSUE TITLE
Can shellsync be add into tree?

### ISSUE THREAD

**Issue by gtcar2020** [robimarko/openwrt#56]
When I attempt to build whith luci-app-syncdial , It notify need shellsync,Can shellsync be add into tree?
Meanwhile I need turboacc also,I have no idea how to add it.

**Comment by robimarko** [comment]
Is that part of OpenWrt or out of tree LuCI app?

**Comment by tm4dev** [comment]
> When I attempt to build whith luci-app-syncdial , It notify need shellsync,Can shellsync be add into tree?
> 
> Meanwhile I need turboacc also,I have no idea how to add it.
> 
> 

For syncdial, did you try mwan3, luci-app-mwan3?

**Comment by gtcar2020** [comment]
yes , I build whith mwan3 and luci-app-mwan3 also.

**Comment by tm4dev** [comment]
> Is that part of OpenWrt or out of tree LuCI app?

Out of tree, I think

**Comment by gtcar2020** [comment]
It' location just like 'openwrt/tree/xxx/package/network/services/shellsync'

**Comment by robimarko** [comment]
Then its not part of OpenWrt, goal of this repo is to get IPQ807x into OpenWrt, not create a fork.
