### ISSUE TITLE
ipq807x: suggestion: Use hotplug scripts to select correct board-2.bin for ath11k

### ISSUE THREAD

**Issue by mrnuke** [robimarko/openwrt#60]
I noticed the ipq-wifi firmware package needs to have a bunch of conflicting board firmware files. The current solution seems to be to have several conflicting packages:

https://github.com/robimarko/openwrt/blob/8c716dcd2045aa7d9b739087f8dfdef59ddb16dc/package/firmware/ipq-wifi/Makefile#L86-L91

Instead, why not use the hotplog scripts to symlink the correct board file to `board-2.bin` ? We already use hotplug for caldata.

**Comment by robimarko** [comment]
The thing is that the files are not conflicting, they are for different radios, it's just a OpenWrt packaging thing that got introduced with ath10k and I just expanded it with ath11k.
So, if this is to change it really needs to be changed universally.

hotplug is great for caldata as that gets extracted from storage during runtime but there is really no advantage to using it from files that are prepackaged.
