### ISSUE TITLE
 When LAN copying files, router CPU usage 20%,NSS can't work?

### ISSUE THREAD

**Issue by ALILEX-1** [robimarko/openwrt#61]
When LAN copying files, Speed can reach 100MB/S.
But router CPU usage 20%, Is it normal?

**Comment by robimarko** [comment]
What usage do you expect?

There is NO OFFLOADING at all.

**Comment by gtcar2020** [comment]
When I use mwan3,The max network speed only reach 500mbps.It seems multiwan does't work at all.(Redmi AX6)

**Comment by ALILEX-1** [comment]
> 

Thank you for your answer
