### ISSUE TITLE
latest source compiled architecture does not display frequency but display temperature!

### ISSUE THREAD

**Issue by zxlhhyccc** [robimarko/openwrt#62]
latest：
![image](https://user-images.githubusercontent.com/45259624/188478919-f68d696e-728c-4bc2-9b1c-6d701be2bc81.png)

old code：
![image](https://user-images.githubusercontent.com/45259624/188478790-3ae187c9-a0de-4223-9db5-9e2f1dbf492f.png)

**Comment by robimarko** [comment]
Is that LuCI or?

Even if it is, that's a LuCI bug

**Comment by robimarko** [comment]
Where is this even shown?

**Comment by zxlhhyccc** [comment]
> Where is this even shown?

architecture：
![image](https://user-images.githubusercontent.com/45259624/188483788-a8a4dd93-e409-4753-80e9-708bdddda2a0.png)

**Comment by robimarko** [comment]
Are you kidding me or what?

Is this LuCI, if so whats the theme, applets etc.
99% this is a generic bug and nothing special to ipq807x

**Comment by zxlhhyccc** [comment]
> Are you kidding me or what?
> 
> Is this LuCI, if so whats the theme, applets etc. 99% this is a generic bug and nothing special to ipq807x

Can I add support for IPQ8071-MF269?

**Comment by robimarko** [comment]
I am getting annoyed with lack of information here, so one last time before I close this.

HOW TO REPRODUCE THIS "ISSUE"?

**Comment by zxlhhyccc** [comment]
> I am getting annoyed with lack of information here, so one last time before I close this.
> 
> HOW TO REPRODUCE THIS "ISSUE"?

Go to Status > Overview > Architecture, shown behind ARMv8

**Comment by kirdesde** [comment]
> > I am getting annoyed with lack of information here, so one last time before I close this.
> > HOW TO REPRODUCE THIS "ISSUE"?
> 
> Go to Status > Overview > Architecture, shown behind ARMv8

This must be a customized LuCI version.

LuCI vanilla doesn't show temperature on the status page.

**Comment by robimarko** [comment]
Ok, that makes sense.

Closing as its clearly a custom LuCI/package issue.
