### ISSUE TITLE
ADD libstdcpp6 and komd-tun for AX 3600

### ISSUE THREAD

**Issue by marcin-admin** [robimarko/openwrt#66]
ADD libstdcpp6 and komd-tun  because it is not in repository and I can not install Zerotier or openvpn.

**Comment by robimarko** [comment]
You mean not shipped by default in the image?

**Comment by marcin-admin** [comment]
I can not install zerotier and openvpn 
![ax3600](https://user-images.githubusercontent.com/108008214/190632204-23942eb9-dd14-474a-bdf4-28a0d9324cd2.jpg)

I will be alsow the solution to add zerotier to image

**Comment by robimarko** [comment]
As explained before, just basic packages are included by default and I dont plan to add anything more.
If you need more kmods then you have to build it yourself or modify the github workflow on your fork
