### ISSUE TITLE
ax9000 ipq807x-2022-09-22-1324 Docker do not work.

### ISSUE THREAD

**Issue by sun9999-dev** [robimarko/openwrt#69]
Images: pulling uweerikmartin/airprint:latest... latest: Pulling from uweerikmartin/airprint ab2d02b1ec42: Pull complete 525acee5a1f9: Extracting [==================================================>]     194B/194B 0f3c490ae51a: Download complete e5bcfa6f6e6d: Download complete 1f80e89737aa: Download complete d084a99fcdde: Download complete 70b38ae55cf1: Download complete 24ab4a100b28: Download complete 18602690b885: Download complete d733681a9741: Download complete 1b41958158be: Download complete code:200 failed to register layer: operation not supported.

docker in debug mode:
INFO[2022-09-25T06:02:20.190775088Z] API listen on /var/run/docker.sock           
DEBU[2022-09-25T06:02:29.388468615Z] Calling HEAD /_ping                          
DEBU[2022-09-25T06:02:29.390128384Z] Calling GET /v1.41/info                      
DEBU[2022-09-25T06:02:29.409725243Z] Calling POST /v1.41/images/create?fromImage=uweerikmartin%2Fairprint&tag=latest 
DEBU[2022-09-25T06:02:29.412726711Z] Trying to pull uweerikmartin/airprint from https://registry-1.docker.io v2 
DEBU[2022-09-25T06:02:32.365871662Z] (*service).Write started                      expected="sha256:0b961ae341dc28c73f2023d498ede99cbc3089856da1f0f853aa1c18a85e6b04" ref="manifest-sha256:0b961ae341dc28c73f2023d498ede99cbc3089856da1f0f853aa1c18a85e6b04" total=2610
DEBU[2022-09-25T06:02:32.368356992Z] Fetching manifest from remote                 digest="sha256:0b961ae341dc28c73f2023d498ede99cbc3089856da1f0f853aa1c18a85e6b04" error="<nil>" remote="docker.io/uweerikmartin/airprint:latest"
DEBU[2022-09-25T06:02:33.321235149Z] Pulling ref from V2 registry: uweerikmartin/airprint:latest 
DEBU[2022-09-25T06:02:33.322832366Z] pulling blob "sha256:0f3c490ae51a6b5bdf1ae36c2239d7097c3b48acf501681a3de53f8fb6d1f114" 
DEBU[2022-09-25T06:02:33.322834345Z] pulling blob "sha256:ab2d02b1ec420fdb84c9f52abda403b6aef20f5de904a2ecda5ae4f5cd6e4d46" 
DEBU[2022-09-25T06:02:33.322947156Z] pulling blob "sha256:525acee5a1f9588ada2f385d502738e5d388fa284868dbd180523412b13d220a" 
DEBU[2022-09-25T06:02:35.998929209Z] Downloaded 525acee5a1f9 to tempfile /tmp/lib/docker/tmp/GetImageBlob2289543823 
DEBU[2022-09-25T06:02:35.999897789Z] pulling blob "sha256:e5bcfa6f6e6dabe12b6593b55e69d59b739c165080b25c1440e48156d0e77750" 
DEBU[2022-09-25T06:02:37.682563301Z] Downloaded e5bcfa6f6e6d to tempfile /tmp/lib/docker/tmp/GetImageBlob3754411787 
DEBU[2022-09-25T06:02:37.683210062Z] pulling blob "sha256:1f80e89737aa9b047b4b23653eed235b17f7700a01367dc1c48b774520c2a287" 
DEBU[2022-09-25T06:02:39.200273636Z] Downloaded ab2d02b1ec42 to tempfile /tmp/lib/docker/tmp/GetImageBlob824401582 
DEBU[2022-09-25T06:02:39.200818785Z] unpigz binary not found, falling back to go gzip library 
DEBU[2022-09-25T06:02:39.201015866Z] pulling blob "sha256:d084a99fcdde58a76fbf13a1e6afdd40aa1a315b7eb5956f4777af05e0fa7365" 
DEBU[2022-09-25T06:02:39.201608461Z] Applying tar in /tmp/lib/docker/overlay2/615703218cbb9c45b7ed7608a60ef79e8ba07e12d5858f08b54bcf4b8bae6f05/diff  storage-driver=overlay2
DEBU[2022-09-25T06:02:40.995077898Z] Downloaded d084a99fcdde to tempfile /tmp/lib/docker/tmp/GetImageBlob1558503453 
DEBU[2022-09-25T06:02:40.995887938Z] pulling blob "sha256:70b38ae55cf1820f3311ec24b3ae07946195d7bf3a4376c79483901dcff2bbb9" 
DEBU[2022-09-25T06:02:41.408038972Z] Downloaded 1f80e89737aa to tempfile /tmp/lib/docker/tmp/GetImageBlob2716182479 
DEBU[2022-09-25T06:02:41.409723531Z] pulling blob "sha256:24ab4a100b28f0ef0793b4077c3ee8ae6ece6b1cbaa350faa04800e4251c2fb6" 
DEBU[2022-09-25T06:02:42.701477211Z] Downloaded 70b38ae55cf1 to tempfile /tmp/lib/docker/tmp/GetImageBlob1658608306 
DEBU[2022-09-25T06:02:42.701650489Z] pulling blob "sha256:18602690b885d61661ffed0ab99c0db40d67299f29d03570dd79f89d518f2dd8" 
DEBU[2022-09-25T06:02:43.812913842Z] Applied tar sha256:942b063c301eb3a3581299227847df70c896991a18216541c4bafb41a4263ffb to 615703218cbb9c45b7ed7608a60ef79e8ba07e12d5858f08b54bcf4b8bae6f05, size: 65593807 
DEBU[2022-09-25T06:02:43.815774063Z] unpigz binary not found, falling back to go gzip library 
DEBU[2022-09-25T06:02:43.816946702Z] Applying tar in /tmp/lib/docker/overlay2/10ca41f003d3cdbe8ad2f8a16b7bcfa550cc5d6d1fcbcda026a9ec78a0ad3eda/diff  storage-driver=overlay2
DEBU[2022-09-25T06:02:43.943992210Z] Applied tar sha256:585d10aeb31437ba0f64ccc3dd382fe8ea8d2ff64161742a6585355ea168b0cd to 10ca41f003d3cdbe8ad2f8a16b7bcfa550cc5d6d1fcbcda026a9ec78a0ad3eda, size: 47 
DEBU[2022-09-25T06:02:44.280075148Z] Downloaded 18602690b885 to tempfile /tmp/lib/docker/tmp/GetImageBlob954254239 
DEBU[2022-09-25T06:02:44.280752482Z] pulling blob "sha256:d733681a97419e439da0c449e39d14158c36930f598b641a604575c834333f85" 
DEBU[2022-09-25T06:02:44.527636516Z] Downloaded 24ab4a100b28 to tempfile /tmp/lib/docker/tmp/GetImageBlob928502046 
DEBU[2022-09-25T06:02:44.528204997Z] pulling blob "sha256:1b41958158be3cfd40d2ce3b7406d851a521368ac3c886a46872d432b65b73c8" 
DEBU[2022-09-25T06:02:45.576865276Z] Downloaded 0f3c490ae51a to tempfile /tmp/lib/docker/tmp/GetImageBlob2572387666 
DEBU[2022-09-25T06:02:45.577384071Z] unpigz binary not found, falling back to go gzip library 
DEBU[2022-09-25T06:02:45.578567023Z] Applying tar in /tmp/lib/docker/overlay2/da7913883222501544f4ce83088f77515d89e4204448242c54dbe7bf1e5dcd1a/diff  storage-driver=overlay2
DEBU[2022-09-25T06:02:45.920996643Z] Downloaded d733681a9741 to tempfile /tmp/lib/docker/tmp/GetImageBlob3223359760 
DEBU[2022-09-25T06:02:46.252563396Z] Downloaded 1b41958158be to tempfile /tmp/lib/docker/tmp/GetImageBlob1551098315 
DEBU[2022-09-25T06:03:00.373412944Z] Cleaning up layer da7913883222501544f4ce83088f77515d89e4204448242c54dbe7bf1e5dcd1a: Error processing tar file(exit status 1): write /usr/lib/udev/hwdb.d/20-OUI.hwdb: no space left on device 
INFO[2022-09-25T06:03:00.556605691Z] Attempting next endpoint for pull after error: failed to register layer: Error processing tar file(exit status 1): write /usr/lib/udev/hwdb.d/20-OUI.hwdb: no space left on device 

but have enough space

OpenWrt# df /opt/docker
Filesystem           1K-blocks      Used Available Use% Mounted on
overlayfs:/overlay    10169016    261568   9366776   3% /
OpenWrt# du -sh /opt/docker 
424.0K	/opt/docker
OpenWrt#

**Comment by robimarko** [comment]
`/usr/lib/udev/hwdb.d/20-OUI.hwdb: no space left on device`

You aint gonna fit hwdb for sure, plus this is completely out of scope of the goals for this project.
