### ISSUE TITLE
hcxdumptool crashes ath11k

### ISSUE THREAD

**Issue by soxrok2212** [robimarko/openwrt#74]
Hi again :) Hope you’re happy to hear from me again. I’m doing some security work and it appears that hcxdumptool crashes ath11k when it hits my network. There’s a variety of things it does (probe request, deauth, ask for pmkid, etc). As soon as I fire it off against my network I see this in dmesg (apologize for crap screenshot, on mobile atm). 

![E5F97D20-B9A8-4A6F-A404-13542FE90DD7](https://user-images.githubusercontent.com/6226507/194976629-29d797fd-3afe-4aa8-9515-20a8de902ab1.png)

At this point, both radio bands go down until reboot.

**Comment by robimarko** [comment]
This is something you are gonna have to open a bugzilla ticket about, I dont see what we can do about it.

**Comment by robimarko** [comment]
This needs to be opened upstream
