### ISSUE TITLE
ipq807x: CONFIG_ATH11K_MEM_PROFILE_1GB=y for 1GB RAM targets?

### ISSUE THREAD

**Issue by DonKult** [robimarko/openwrt#78]
Hi,

`CONFIG_ATH11K_MEM_PROFILE_512MB` is brought in via a patch and used by default. Is it intended that the profile is kept at the default even for the targets which come with 1GB of RAM like the last four added or is that a remnant from the three earlier targets all being 512MB?

I compiled & tested on dl-wrx36 with the 1GB profile, but of course I am miles away from a usage pattern in which it would actually matter, I can just confirm that it doesn't explode on boot :wink: – and am just curious, trying to learn a thing or two in the process of poking around (so, feel free to tell me to stop).

**Comment by robimarko** [comment]
Sorted out indirectly by completely reworking the profile selection logic.
Whole logic got completely removed and now the driver parses the FW mode from DTS so its completely per board and not compile time defined anymore so all 1G devices are using Mode 0 which is appropriate for them now.
