### ISSUE TITLE
Which branch is the lastest stable for rb450gx4?

### ISSUE THREAD

**Issue by swordow** [robimarko/openwrt#83]
I found that there are some branches for rbg450gx4 and which one is the lastest stable for it ? And if it contains the sd card supports?

**Comment by robimarko** [comment]
None really, I dont have the board anymore.

**Comment by swordow** [comment]
> None really, I dont have the board anymore.

Oh...bad news..ahh.
And which branch is better that i could continue developing on for rb450gx4 ?
Thanks.

**Comment by robimarko** [comment]
None of mine, john-tho has much newer stuff for RB450Gx4 and support for the new NAND revision
https://github.com/john-tho/openwrt

**Comment by swordow** [comment]
> None of mine, john-tho has much newer stuff for RB450Gx4 and support for the new NAND revision https://github.com/john-tho/openwrt

Thanks. I will try it~~
