### ISSUE TITLE
ipq807x-6.1-AX3600 编译失败

### ISSUE THREAD

**Issue by Lancet-z** [robimarko/openwrt#87]
Hunk #1 FAILED at 509.
1 out of 1 hunk FAILED -- saving rejects to file drivers/of/platform.c.rej
patching file drivers/soc/qcom/smem.c
Hunk #1 FAILED at 9.
Hunk #2 FAILED at 240.
Hunk #3 FAILED at 499.
Hunk #4 FAILED at 664.
Hunk #5 FAILED at 863.
Hunk #6 FAILED at 881.
Hunk #7 FAILED at 895.
Hunk #8 FAILED at 914.
8 out of 8 hunks FAILED -- saving rejects to file drivers/soc/qcom/smem.c.rej
Patch failed!  Please fix /home/xxxx/openwrt/target/linux/ipq807x/patches-5.15/0008-v5.16-soc-qcom-smem-Support-reserved-memory-description.patch!
make[4]: *** [Makefile:32: /home/xxxxx/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.15.74/.prepared_7cf92f390b8f2b764aac616a7e39bd92] Error 1
make[4]: Leaving directory '/home/xxxxxx/openwrt/target/linux/ipq807x'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/xxxxxxx/openwrt/target/linux'
time: target/linux/compile#10.12#5.12#12.57
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/home/xxxxxx/openwrt'
make[1]: *** [target/Makefile:23: /home/xxxxxx/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/xxxxxxx/openwrt'
make: *** [/home/lancet/openwrt/include/toplevel.mk:231: world] Error 2

想问下是我配置有误吗。

**Comment by robimarko** [comment]
No idea what this is supposed to be
