### ISSUE TITLE
please we need kmod-tun package to allow open vpn

### ISSUE THREAD

**Issue by aliweb1991** [robimarko/openwrt#90]
please we need **kmod-tun** package to allow open vpn

**Comment by aliweb1991** [comment]
I can't find away to install openvpn-ssl  to "ax3600"

could you please help , appreciate your great work

**Comment by robimarko** [comment]
Install the latest version and install the required packages via opkg

**Comment by javykhan** [comment]
Any chance for kmod-wireguard?

**Comment by robimarko** [comment]
All of the kmods can be installed that way, but you have to use the latest release
