### ISSUE TITLE
Device reload when trying to create interface in monitor mode on radio phy

### ISSUE THREAD

**Issue by AlexeiGHub** [robimarko/openwrt#96]
For a safe try  "iw phy phy**0|1** interface add mon0 type monitor "  or in LuCI.

Try on LuCI BootLooping device.

My device Redmi AX6.

**Comment by robimarko** [comment]
Thanks for reporting this, it has already been fixed upstream, so I will backport the patch that fixes it.

**Comment by robimarko** [comment]
Fix has been added and pushed, so CI is building new images.
