### ISSUE TITLE
Slow Ethernet connection on AX3600

### ISSUE THREAD

**Issue by josemmc95** [robimarko/openwrt#97]
Hey there.

I'm getting up to ~450mbs download speed from ethernet ports. I usually get ~800mbs with the original firmware.

Is there anything I have to set to get full speed?

Thank you in advanced.

**Comment by robimarko** [comment]
There is no offloading at all, so speeds are gonna be lower depending on what you are doing

**Comment by robimarko** [comment]
Yeah, please check out the forum thread posts by user dchard, he is using PPoE and squeezes around 800-ish Mbps with some tweaks.

**Comment by josemmc95** [comment]
Fixed enabling Packet Steering in Network - Interfaces - Global network options.
